### ISSUE TITLE
4.8 Release Plan

### ISSUE THREAD

**Issue by jasongrout** [jupyter/jupyter_core#235]
It's been a while since we had a release, and we have a number of good PRs that have been merged. I created a 4.8 milestone with the PRs that have been merged: https://github.com/jupyter/jupyter_core/milestone/20?closed=1

Is there anything else someone feels strongly should go into 4.8? I'm happy to start the release process with a prerelease.

CC @kevin-bates, who did the last several releases.

**Comment by kevin-bates** [comment]
Thank you @jasongrout!

**Comment by jasongrout** [comment]
I tried releasing 4.8.0b0, but it turns out I don't have pypi permissions to release jupyter_core (https://pypi.org/project/jupyter-core/). Can someone give me (`jasongrout`) permissions on pypi to release jupyter_core?

**Comment by blink1073** [comment]
Done!

**Comment by jasongrout** [comment]
> Done!

Thanks. I'm still not showing up in the list of maintainers at https://pypi.org/project/jupyter-core/ (maybe it's a caching issue?)

**Comment by jasongrout** [comment]
> Thanks. I'm still not showing up in the list of maintainers at https://pypi.org/project/jupyter-core/ (maybe it's a caching issue?)

Sorry, I didn't see the email that I needed to accept it first.

**Comment by jasongrout** [comment]
I've released 4.8.0b0. I'll plan to release rc0 early next week if there are no objections. Again, if someone wants to get something else in for 4.8.0, please comment here before next week.

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/jupyter-core-4-8-0-release-candidate/10470/1

**Comment by jasongrout** [comment]
I just released 4.8.0rc0 and posted about the release candidate on Discourse. You can install the RC with `pip install --pre jupyter_core==4.8.0rc0`

Can a few people test it and post here (good or bad)? I propose we release 4.8.0 early next week if we hear only good reports.

**Comment by blink1073** [comment]
I ran `jupyterlab` at [master](https://github.com/jupyterlab/jupyterlab/commit/68a6066dc03dc7cc76141ae78e945faf99da5205) against `jupyter_core==4.8.0rc0` on my 
MacBook Air.  Unit tests pass and the application is fully functional.  I tested the relevant CLI changes as well:

```
jupyter
jupyter help
jupyter --version
jupyter lab --show-config
```

**Comment by bollwyvl** [comment]
I think we need to actually test the pypy vs win stuff... could wait to do so on conda-forge, but it's probably better to have it here so we're not drag-netting upstream issues _after_ it's been released... and `jupyter_core` isn't something fun have have broken.

PR incoming...

**Comment by bollwyvl** [comment]
Yep, looks like #237 needs some more love. I'm not qualified (or _particularly_ interested) in the _how_ of fixing windows pypy issues, but would like to see them fixed, if somebody's hot on it, so we don't have to deal with it downstream...

**Comment by bollwyvl** [comment]
I've taken #237 as far as i can, looks like `is_hidden` is (only) failing on win/pypy at this point... cc @cgohlke @stonebig as y'all seemed interested in #230, any thoughts?

otherwise, `py3.10` is also good to go, save for on (surprise) windows, where `pywin32` is not available yet.

**Comment by cgohlke** [comment]
> is_hidden is (only) failing on win/pypy

`is_hidden` does not currently work on pypy due to a [missing os.stat attribute](https://foss.heptapod.net/pypy/pypy/-/issues/3469). See comment at https://github.com/jupyter/jupyter_core/blob/f5660f67ae2257e183a440022bb0a668bd21246c/jupyter_core/paths.py#L271-L278

> py3.10 is also good to go, save for on (surprise) windows, where pywin32 is not available yet

#230 should take care of that. Pywin32 is no longer necessary. Just exclude pywin32 as a requirement on Python 3.10 for Windows or remove it altogether.
 https://github.com/jupyter/jupyter_core/blob/f96b3db350375ed2391c1761e3766f7e2af12cba/setup.cfg#L27

**Comment by bollwyvl** [comment]
Great, i'll add the skip for `is_hidden` and reference the linked issue in the reason.

> Pywin32 is no longer necessary. 

Perhaps not, but it _is_ what we've been running for a number of years, and this package is likely expected as the keeper of the `pywin32` dependency for a number of downstreams. 

I am unfamiliar with the new, relatively large codebase that landed in #230... without these tests/skips I am now having to write, and somewhat question why we couldn't move this implementation out of `jupyter_core` into a separate compatibility package... or better still land them _in_ `pywin32`, so they benefit other packages.

**Comment by bollwyvl** [comment]
#237 is now :green_circle: without changing any dependencies. It looks like a pywin32 that supports 3.10 isn't _too_ far off, either, so we can likely defer that decision until after this release.

**Comment by bollwyvl** [comment]
Note that the `is_hidden` issue may _directly_ impact the user experience here: https://github.com/jupyter-server/jupyter_server/blob/e3a146e5380f8a2d03145725617e83cc0abd8322/jupyter_server/services/contents/filemanager.py#L17

Perhaps we need a `warning`?

**Comment by jasongrout** [comment]
Is this an accurate summary of the `is_hidden` issue: on PyPy for windows, `is_hidden` (which delegates to `is_file_hidden_win`) will never claim that a file is hidden, even if the file really is hidden.

If so, then I agree that we should at least have a warning when using the function on PyPy that the function will not behave as expected, especially if we are saying we support pypy in this release.

Should we go further in throwing an error instead of ignoring the error at https://github.com/jupyter/jupyter_core/blob/f5660f67ae2257e183a440022bb0a668bd21246c/jupyter_core/paths.py#L271-L278

It seems like a bad idea if a check for a hidden file claims that the file is not hidden when it really is. As Nick points out, we use that check to see what files to display in the Jupyter Notebook and JupyterLab, for example. Throwing an error in that is_hidden check I think would mean that Jupyter Lab would not work on pypy, though.

**Comment by jasongrout** [comment]
Or we could say our pypy support is experimental, with these known issues: hidden files appear to not be hidden, ....

**Comment by jasongrout** [comment]
I take @stonebig's heart on my last comment to mean that they support that approach. Any other comments? I see two options:

1. Throw an error in the hidden file function, which means that if you use that function on pypy, your application will not work.
2. Publish and explain in the release notes that pypy support is experimental, and throw a warning in the exception to alert the user at runtime.

**Comment by jasongrout** [comment]
> Publish and explain in the release notes that pypy support is experimental, and throw a warning in the exception to alert the user at runtime.

This is now implemented in https://github.com/jupyter/jupyter_core/pull/238, waiting for review.

**Comment by stonebig** [comment]
os.stat attribute  will arrive [in PyPy-7.3.6 imminent release ](https://foss.heptapod.net/pypy/pypy/-/issues/3469#note_163119 ) 

("imminent" = it was said last week, last week)

**Comment by jasongrout** [comment]
I released 4.8.0rc1 with #238 to warn about missing hidden file attributes.

Please test. If there are no further comments or objections, I'll plan to release 4.8.0 final next Thursday.

**Comment by jasongrout** [comment]
4.8.0 is now released: https://pypi.org/project/jupyter-core/4.8.0/

Conda-forge package will come soon.
